### ISSUE TITLE
Suggestion: looser search

### ISSUE THREAD

**Issue by BGMcoder** [dragan224/battle_cats_en_combos#2]
Say I want to find combos that use Artist Cat.  I propose a couple of ideas to make this app easier to use:
1.  Looser search - let me type simply "artist"  instead of "Artist Cat"
2.  Let it filter the list as I type instead of just waiting for me to push the "search" button.

The looser search would let me find the "Ururun Wolf" by typing "wolf" in case I don't know how to spell "Ururun".

Just ideas!  But it's just a simple list filter, so you might not want to spend that much time on it.

**Comment by dragan224** [comment]
Done,

Re-download the app,

**Comment by BGMcoder** [comment]
Wow!  You are wonderful!    Now it is soooo much more usable!  This is perfect!  Thanks so much!
